### ISSUE TITLE
appveyor windows ci python issues preventing builds

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#848]
appveyor windows ci conda setup started failing (config has been static for a very very long time) 

With miniconda 3.6:

```
Verifying transaction: ...working... done
Executing transaction: ...working... failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'defaults::charset-normalizer-2.0.4-pyhd3eb1b0_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda36\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Attempting to roll back.
Rolling back transaction: ...working... done
CondaError: Cannot link a source that does not exist. C:\Miniconda36\Scripts\conda.exe
Running `conda clean --packages` may resolve your problem.
Command exited with code 1
```

Trying newer (miniconda 3.7) fails in a different way -- it doesn't install a viable numpy.
```
python -c "import numpy as n; print(n.__version__); print(n.get_include());"
C:\Miniconda3\lib\site-packages\numpy\__init__.py:148: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Miniconda3\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Miniconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Miniconda3\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core
  File "C:\Miniconda3\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
    https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
  * The Python version is: Python3.7 from "C:\Miniconda3\python.exe"
  * The NumPy version is: "1.21.2"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: DLL load failed: The specified module could not be found.
Command exited with code 1
```

**Comment by cyrush** [comment]
resolved in #751
